- name: Get EC2 Instance IPs
  hosts: localhost # This playbook runs locally

  tasks:
    - name: Gather EC2 instance information
      amazon.aws.ec2_instance_info:

      #  region: "ap-south-1" # Replace with your AWS region
      register: ec2_info
    - name: Install package
      ansible.builtin.package:
        name: "httpd"
        state: present
    # - name: Display IP addresses
    #   debug:
    #     #msg: "My ip is {{ item.public_ip_address  }}"
    #     # msg: "My ip is {{ ec2_info.instances[0].network_interfaces[0].association.public_ip }}"
    #   with_items: "{{ ec2_info.instances.public_ip_address }}"

    - name: Display Public IP
      ansible.builtin.debug:
        msg: "{{ item.public_ip_address }}"
      # with_items: "{{ ec2_info.instances | map(attribute='public_ip_address') | list }}"
      with_items: "{{ ec2_info.instances }}"
